# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 12
paginate_path: "/page/:num"
language: 'pt-br'

source: "src"
url: "https://blog.nandomoreira.me"

# Website info
title: Nando's blog
description: Desenvolvedor front-end e entusiasta da experiência do usuário | Desenvolvedor Front-end em Curitiba | Desenvolvedor WordPress em Curitiba | UX Designer em Curitiba
cover: assets/images/blog-cover.png
logo: false
favicon: assets/images/favicon.png

# Social info
github: nandomoreirame
twitter: oseunando
instagram: oseunando
linkedin: nandomoreirame
facebook: oseunando

# Disqus
disqus: true
disqus_shortname: fernandomoreira

# Google Analytics
google_analytics: UA-119443578-1

# Permalinks
permalink: /:title

# Tags' info in `_data/tags_info.yml`
plugins_dir: ./_plugins

# gems and other configs
plugins:
  - jekyll-youtube
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

feed:
  path: feed.xml

compress_html:
  clippings: all
  comments:  all
  endings: all
  ignore:
    envs: ['development', 'local']
  blanklines: false
  profile: false
  startings: [html, head, body]

include:
  - _redirects

exclude:
  - assets/css
  - node_modules
  - vendor
  - Gemfile
  - Gemfile_
  - gulpfile.js
  - LICENSE
  - package.json
  - README.md
  - ./*.lock
  - .git*
